### ISSUE TITLE
Peer-Review-1 sumering

### ISSUE THREAD

**Issue by rn222cx** [ad222kr/1dv450-registration#10]
Det var inga problem att få igång applikationen samt köra seeds filen. Det är snålt med kommentarer men jag hade inga problem med att förstå koden för det. Koden var talande med bra namngivningar.
Bra uppdelning av koden vad det gäller vyer och kontroller.

Det negativa finns ju såklart i issues.

Jag har inte granskat någon html eller css kod som säkerligen förmodar.

Mvh

Roy

**Comment by alexdriaguine** [comment]
Tack för kommentarerna, ska åtgärda snarast!

**Comment by 1dv450** [comment]
:+1:
