### ISSUE TITLE
Oanvänd kod i AppController

### ISSUE THREAD

**Issue by rn222cx** [ad222kr/1dv450-registration#3]
Dessa rader kan städas bort i AppController.

https://github.com/rn222cx/1dv450-registration/blob/master/app/controllers/apps_controller.rb#L2#L7
https://github.com/rn222cx/1dv450-registration/blob/master/app/controllers/apps_controller.rb#L28#L30
https://github.com/rn222cx/1dv450-registration/blob/master/app/controllers/apps_controller.rb#L43#L45

**Comment by alexdriaguine** [comment]
fetch_app  körs innan show och destroy så man inte behöver skriva App.find(params[:id]) överallt, förstår inte riktigt vad du menar med att den är oanvänd.

Felet jag ser är att den inte satte värdet till @app. Argumentera gärna för för jag har svårt att förstå vad du menar här

**Comment by alexdriaguine** [comment]
Eh, nvm. Fattar nu. Trodde detta var UserController... Dags att börja läsa allt innan man drar slutsatser :P
