### ISSUE TITLE
Förändra apps struktur

### ISSUE THREAD

**Issue by rn222cx** [ad222kr/1dv450-registration#6]
Den här är en alternativ förändring som kommer göra dina url tillhörande apps kortare och snyggare samt minimering av kod

I routes ändra

``` ruby
  resources :users do
    resources :apps
  end
```

till

``` ruby
    resources :apps, only: [:new, :create, :destroy]
    resources :users, except: [:index, :destroy]
```

I UserController ändra rad 13 till

``` ruby
@apps = @user
```

I views/users/show.html.erb ta bort från rad 30 och neråt.
Ersätt med

``` ruby
      <% if @user.admin?
           args = @apps
         else
           args = @apps.apps
         end %>


      <% args.each do |app| %>
          <tr>
            <td><%= app.name %></td>
            <td><%= app.api_key %></td>
            <td><%= app.user.name %></td>
            <td><%= link_to "Remove application", app,
                            method: :delete,
                            data: {confirm: "Are you sure you want to remove this app?"} %></td>
          </tr>

      <% end %>
    </table>

  </div>
</div>

<div class="row">
  <div class="col-mod-4 text-center">
    <%= link_to "Register application", new_app_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>
```

Nu kan user objektet tas bort i AppsController (se länk)
https://github.com/rn222cx/1dv450-registration/blob/master/app/controllers/apps_controller.rb#L11

Samt i tillhörande vyi rad 4

``` ruby
<%= form_for [@user, @app] do |f| %>
```

till

``` ruby
<%= form_for(@app) do |f| %>
```

**Comment by alexdriaguine** [comment]
Nice, tack! Blev finare URLS. Fixat. Har dock kvar att @apps sätts i controllern istället för i vyn, tycker att data ska förberedas så mycket som möjligt innan det skjuts in i vyn.

**Comment by rn222cx** [comment]
Du skulle kunna använda index för admin. Slipper du tänka på både vanliga användare samt admin i samma vy/controller
