### ISSUE TITLE
Logout security

### ISSUE THREAD

**Issue by rn222cx** [ad222kr/1dv450-registration#8]
Jag klistra direkt in en issue från min egna peer review som jag fick av Singh, då du lider av samma säkerhets brist

> Ett säkerhetshål i applikation som jag fick reda från min peer-review. När man varit inloggad och loggar ut och trycker på tillbaka knappen så visas sidan man tidigare var inne på. T.ex att användaren har domän sida framme (med API nycklar), loggar ut och sen lämnar datorn utan att lämna sidan eller stänga webbläsaren så kan en annan person komma åt informationen på den sidan, bara genom att testa att klicka på backa knappen.
> 
> Lösningen som jag har att erbjuda delades med mig av mv222fp/Marco30.
> Det hindra cachning genom att lägga till följande i ApplicationController och lägga till data: {no_turbolink: true} i logout länken.
> 
> Länken i app/views/layouts/_header.html.erb
> 
> <%= link_to "Log out", logout_path, data: {no_turbolink: true}, class: "nav-link-right" %>
> app/controllers/application_controller.rb
> 
> before_action :no_cache
> 
> def no_cache
>   response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
>   response.headers["Pragma"] = "no-cache"
>   response.headers["Expires"] = "Fri, 09 Jan 2004 00:00:00 GMT"
> end

**Comment by alexdriaguine** [comment]
Fixat!
